services:
  web:
    build: ../frontend/
    ports:
      - 3000:3000

  back:
    build: ../backend/
    ports:
      - 8081:8081
      - 8080:8080

  db:
    image: postgres:12.19-bookworm
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: ./secret/postgres-psswd
    volumes:
      - ./postgres:/data/db
