services:
  web:
    build: ../frontend/
    ports:
      - 3000:3000

  back:
    build: ../backend/
    ports: 
      - 8081:8081
      - 8080:8080

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ./secret/mongo-psswd
    volumes:
      - ./mongodb:/data/db
