// <auto-generated />
using System;
using EntityFramework.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EntityFramework.Migrations
{
    [DbContext(typeof(HestiaContext))]
    partial class HestiaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EntityFramework.Models.Chore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ColocationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDone")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("ColocationId");

                    b.HasIndex("CreatedBy");

                    b.ToTable("Chores");
                });

            modelBuilder.Entity("EntityFramework.Models.ChoreEnrollment", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChoreId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("UserId", "ChoreId");

                    b.HasIndex("ChoreId");

                    b.ToTable("ChoreEnrollments");
                });

            modelBuilder.Entity("EntityFramework.Models.Colocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Colocations");
                });

            modelBuilder.Entity("EntityFramework.Models.Entry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(19,2)");

                    b.Property<Guid>("ColocationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("ExpenseId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ColocationId");

                    b.HasIndex("ExpenseId");

                    b.HasIndex("UserId");

                    b.ToTable("Entries");
                });

            modelBuilder.Entity("EntityFramework.Models.Expense", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(19,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateOfPayment")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("ExpenseCategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PaidBy")
                        .HasColumnType("uuid");

                    b.Property<string>("SplitType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ExpenseCategoryId");

                    b.HasIndex("PaidBy");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("EntityFramework.Models.ExpenseCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ColocationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ColocationId");

                    b.ToTable("ExpenseCategories");
                });

            modelBuilder.Entity("EntityFramework.Models.FCMDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FCMToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("FCMDevices");
                });

            modelBuilder.Entity("EntityFramework.Models.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ColocationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("SentBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ColocationId");

                    b.HasIndex("SentBy");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("EntityFramework.Models.PollVote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Choice")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PollReminderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("VotedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("VotedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PollReminderId");

                    b.HasIndex("VotedBy");

                    b.ToTable("PollVotes");
                });

            modelBuilder.Entity("EntityFramework.Models.Reaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("ReminderId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ReminderId");

                    b.HasIndex("UserId");

                    b.ToTable("Reactions");
                });

            modelBuilder.Entity("EntityFramework.Models.Reminder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ColocationId")
                        .HasColumnType("uuid");

                    b.Property<int>("CoordX")
                        .HasColumnType("integer");

                    b.Property<int>("CoordY")
                        .HasColumnType("integer");

                    b.Property<int>("CoordZ")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("ReminderType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.HasKey("Id");

                    b.HasIndex("ColocationId");

                    b.HasIndex("CreatedBy");

                    b.ToTable("Reminders");

                    b.HasDiscriminator<string>("ReminderType").HasValue("Reminder");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("EntityFramework.Models.ShoppingItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsChecked")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ShoppingListReminderId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ShoppingListReminderId");

                    b.ToTable("ShoppingItems");
                });

            modelBuilder.Entity("EntityFramework.Models.SplitBetween", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ExpenseId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.HasKey("UserId", "ExpenseId");

                    b.HasIndex("ExpenseId");

                    b.ToTable("SplitBetweens");
                });

            modelBuilder.Entity("EntityFramework.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ColocationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastConnection")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("PathToProfilePicture")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ColocationId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EntityFramework.Models.ImageReminder", b =>
                {
                    b.HasBaseType("EntityFramework.Models.Reminder");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("Image");
                });

            modelBuilder.Entity("EntityFramework.Models.PollReminder", b =>
                {
                    b.HasBaseType("EntityFramework.Models.Reminder");

                    b.Property<bool>("AllowMultipleChoices")
                        .HasColumnType("boolean");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsAnonymous")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("Poll");
                });

            modelBuilder.Entity("EntityFramework.Models.ShoppingListReminder", b =>
                {
                    b.HasBaseType("EntityFramework.Models.Reminder");

                    b.Property<string>("ShoppingListName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("ShoppingList");
                });

            modelBuilder.Entity("EntityFramework.Models.TextReminder", b =>
                {
                    b.HasBaseType("EntityFramework.Models.Reminder");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("Text");
                });

            modelBuilder.Entity("EntityFramework.Models.Chore", b =>
                {
                    b.HasOne("EntityFramework.Models.Colocation", "Colocation")
                        .WithMany("Chores")
                        .HasForeignKey("ColocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityFramework.Models.User", "User")
                        .WithMany("Chores")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Colocation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EntityFramework.Models.ChoreEnrollment", b =>
                {
                    b.HasOne("EntityFramework.Models.Chore", "Chore")
                        .WithMany("ChoreEnrollments")
                        .HasForeignKey("ChoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityFramework.Models.User", "User")
                        .WithMany("ChoreEnrollments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chore");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EntityFramework.Models.Entry", b =>
                {
                    b.HasOne("EntityFramework.Models.Colocation", "Colocation")
                        .WithMany()
                        .HasForeignKey("ColocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityFramework.Models.Expense", "Expense")
                        .WithMany("Entries")
                        .HasForeignKey("ExpenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityFramework.Models.User", "User")
                        .WithMany("Entries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Colocation");

                    b.Navigation("Expense");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EntityFramework.Models.Expense", b =>
                {
                    b.HasOne("EntityFramework.Models.ExpenseCategory", "ExpenseCategory")
                        .WithMany("Expenses")
                        .HasForeignKey("ExpenseCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityFramework.Models.User", "User")
                        .WithMany("Expenses")
                        .HasForeignKey("PaidBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExpenseCategory");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EntityFramework.Models.ExpenseCategory", b =>
                {
                    b.HasOne("EntityFramework.Models.Colocation", "Colocation")
                        .WithMany("ExpenseCategories")
                        .HasForeignKey("ColocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Colocation");
                });

            modelBuilder.Entity("EntityFramework.Models.FCMDevice", b =>
                {
                    b.HasOne("EntityFramework.Models.User", "User")
                        .WithMany("FCMDevices")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EntityFramework.Models.Message", b =>
                {
                    b.HasOne("EntityFramework.Models.Colocation", "Colocation")
                        .WithMany("Messages")
                        .HasForeignKey("ColocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityFramework.Models.User", "User")
                        .WithMany("Messages")
                        .HasForeignKey("SentBy")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Colocation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EntityFramework.Models.PollVote", b =>
                {
                    b.HasOne("EntityFramework.Models.PollReminder", "PollReminder")
                        .WithMany("PollVotes")
                        .HasForeignKey("PollReminderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityFramework.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("VotedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PollReminder");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EntityFramework.Models.Reaction", b =>
                {
                    b.HasOne("EntityFramework.Models.Reminder", "Reminder")
                        .WithMany("Reactions")
                        .HasForeignKey("ReminderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityFramework.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reminder");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EntityFramework.Models.Reminder", b =>
                {
                    b.HasOne("EntityFramework.Models.Colocation", "Colocation")
                        .WithMany("Reminders")
                        .HasForeignKey("ColocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityFramework.Models.User", "User")
                        .WithMany("Reminders")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Colocation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EntityFramework.Models.ShoppingItem", b =>
                {
                    b.HasOne("EntityFramework.Models.ShoppingListReminder", "ShoppingListReminder")
                        .WithMany("ShoppingItems")
                        .HasForeignKey("ShoppingListReminderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShoppingListReminder");
                });

            modelBuilder.Entity("EntityFramework.Models.SplitBetween", b =>
                {
                    b.HasOne("EntityFramework.Models.Expense", "Expense")
                        .WithMany("SplitBetweens")
                        .HasForeignKey("ExpenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityFramework.Models.User", "User")
                        .WithMany("SplitBetweens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("Expense");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EntityFramework.Models.User", b =>
                {
                    b.HasOne("EntityFramework.Models.Colocation", "Colocation")
                        .WithMany("Users")
                        .HasForeignKey("ColocationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Colocation");
                });

            modelBuilder.Entity("EntityFramework.Models.Chore", b =>
                {
                    b.Navigation("ChoreEnrollments");
                });

            modelBuilder.Entity("EntityFramework.Models.Colocation", b =>
                {
                    b.Navigation("Chores");

                    b.Navigation("ExpenseCategories");

                    b.Navigation("Messages");

                    b.Navigation("Reminders");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("EntityFramework.Models.Expense", b =>
                {
                    b.Navigation("Entries");

                    b.Navigation("SplitBetweens");
                });

            modelBuilder.Entity("EntityFramework.Models.ExpenseCategory", b =>
                {
                    b.Navigation("Expenses");
                });

            modelBuilder.Entity("EntityFramework.Models.Reminder", b =>
                {
                    b.Navigation("Reactions");
                });

            modelBuilder.Entity("EntityFramework.Models.User", b =>
                {
                    b.Navigation("ChoreEnrollments");

                    b.Navigation("Chores");

                    b.Navigation("Entries");

                    b.Navigation("Expenses");

                    b.Navigation("FCMDevices");

                    b.Navigation("Messages");

                    b.Navigation("Reminders");

                    b.Navigation("SplitBetweens");
                });

            modelBuilder.Entity("EntityFramework.Models.PollReminder", b =>
                {
                    b.Navigation("PollVotes");
                });

            modelBuilder.Entity("EntityFramework.Models.ShoppingListReminder", b =>
                {
                    b.Navigation("ShoppingItems");
                });
#pragma warning restore 612, 618
        }
    }
}
