name: Run .NET Tests

on:
  push:
    branches: [ main, develop ] # Exécute les tests sur les branches principales
  pull_request:
    branches: [ main, develop ] # Exécute les tests lors d'une Pull Request (PR)

jobs:
  test:
    runs-on: ubuntu-latest  # Utilise un runner GitHub avec Ubuntu

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Récupère le code source

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x' # Remplace par ta version de .NET si différente

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --no-restore

      - name: Run tests
        run: dotnet test --no-build --verbosity normal
